### ISSUE TITLE
When to unbind

### ISSUE THREAD

**Issue by tonyxiao** [SwiftBond/Bond-Demo-App#1]
https://github.com/SwiftBond/Bond-Demo-App/blob/master/BondDemo/ListCellView.swift#L21

Why is it that it's only necessary to unbind the avatarImageView? What about nameLabel and ownerLabel? Shouldn't they be unbind upon `prepareForReuse` also?

**Comment by srdanrasic** [comment]
It would be better to unbind all. Fixed.
